core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('', include('users.urls')),
]

core/crm/urls.py
from django.urls import path
from .views import IndexView

app_name = 'crm'


urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

core/users/urls.py
from django.urls import path
from .views import signup, signin, signout, profile

app_name = 'user'


urlpatterns = [
    path('register/', signup, name='register'),
    # Users Login
    path('login/', signin, name='login'),
    path('profile/', profile, name='profile'),  # User profile

    path('logout/', signout, name='logout'),
]

core/crm/models.py
from django.db import models

# Create your models here.

core/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, username, firstname, lastname, password, active=True, staff=False, admin=False):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            firstname=firstname,
            lastname=lastname
        )
        user.set_password(password)  # change user password
        user.staff = staff
        user.admin = admin
        user.active = active
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, firstname, lastname, password):
        user = self.create_user(
            email,
            username,
            firstname,
            lastname,
            password,
            staff=True,
            admin=True,
            active=True

        )
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=100, blank=False, unique=True)
    username = models.CharField(verbose_name='username', max_length=30, unique=True)
    firstname = models.CharField(verbose_name='firstname', max_length=30, blank=True)
    lastname = models.CharField(verbose_name='lastname', max_length=30, blank=True)

    active = models.BooleanField(default=True)  # can login
    staff = models.BooleanField(default=False)  # staff user non superuser
    admin = models.BooleanField(default=False)  # superuser
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # confirm     = models.BooleanField(default=False)
    # confirmed_date     = models.DateTimeField(default=False)

    USERNAME_FIELD = 'email'  # username
    # USERNAME_FIELD and password are required by default
    REQUIRED_FIELDS = ['username', 'firstname', 'lastname']  # ['full_name'] #python manage.py createsuperuser

    class Meta:
        verbose_name = "Account"
        verbose_name_plural = "Accounts"

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_firstname(self):
        if self.firstname:
            return self.firstname
        return self.email

    def get_lastname(self):
        if self.lastname:
            return self.lastname
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, obj=None):
        return self.admin

    def has_module_perms(self, app_label):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

core/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text="Required.Add a valid email address.")

    class Meta:
        model = User
        fields = ('email', 'firstname', 'lastname', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            User.objects.get(email=email)
        except:
            return email
        raise forms.ValidationError(f"Email {email} s already in use.")

    def clean_firstname(self):
        firstname = self.cleaned_data['firstname']
        try:
            User.objects.get(firstname=firstname)
        except:
            return firstname

    def clean_lastname(self):
        lastname = self.cleaned_data['lastname']
        try:
            User.objects.get(lastname=lastname)
        except:
            return lastname

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        try:
            User.objects.get(username=username)
        except:
            return username
        raise forms.ValidationError(f"Username {username} s already in use.")


class LoginForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid Login")

core/crm/views.py
from django.views.generic import TemplateView


# Create your views here.

class IndexView(TemplateView):
    template_name = "crm/index.html"

core/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout

from .forms import RegisterForm, LoginForm


# Create your views here.

def signup(request, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f"You are already authenticated as {user.email}.")
    context = {}

    if request.POST:
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            destination = kwargs.get("next")
            if destination:
                return redirect(destination)
            return redirect("crm:index")
        else:
            context['RegisterForm'] = form

    return render(request, 'users/signup/register.html', context)


def signin(request, *args, **kwargs):
    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect('user:profile')
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect('destination')
                return redirect('user:profile')
        else:
            context['LoginForm'] = form
    return render(request, 'users/signin/login.html', context)


def signout(request):
    logout(request)
    return redirect("crm:index")


def get_redirect_if_exists(request):
    reroute = None
    if request.GET:
        if request.GET.get('next'):
            reroute = str(request.GET.get('next'))
    return reroute


def profile(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    else:
        return render(request, 'users/signin/profile.html')

core/templates/crm/index.html
{% extends "layouts/base.html" %}

    {% block content %}
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="bootstrap-themes.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">CRM built with Django</h1>
        <p class="lead">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Primary</button>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">Default</button>
        </div>
      </div>
    </div>
  </div>

          {% if request.user.is_authenticated %}
<div class="container justify-content-center">Hi user, {{user.email}}</div>
{% else %}

<div class="container justify-content-center">Is not authenticated</div>
{% endif %}
    {% endblock content %}

core/templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM project 0.0.1</title>
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>
  <div >
      {% include 'layouts/navbar.html' %}
  </div>

    <div>

    {% block content %}

    {% endblock content %}

    </div>
  <!-- Scripts JS File -->
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

  <!-- Bootstrap Bundle  -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'crm:index' %}">
      <img src="{% static '/img/logo.png' %}" alt="Logo" width="35" height="35" class="d-inline-block align-text-top">
      -CRM
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 ">
        <li class="nav-item">
          <a class="nav-link" href="#">Функциональность</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Доступности</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">О Нас</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex align-items-center">
        <div class="flex-shrink-0 dropdown me-3">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Язык
          </a>
          <ul class="dropdown-menu text-small shadow">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
          </ul>
        </div>
        <div class="nav">
             {% if request.user.is_authenticated %}
          <a type="button" class="btn btn-outline-primary me-2" href="{% url 'user:logout' %}">Logout</a>
          {% else %}
          <a type="button" class="btn btn-outline-primary me-2" href="{% url 'user:login' %}">Login</a>
          <a type="button" class="btn btn-outline-primary" href="{% url 'user:register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

core/templates/users/signin/login.html
{% extends "layouts/base.html" %}
{% load static %}
{% include 'layouts/navbar.html' %}

{% block content%}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="card card-signin">
            <div class="card-body">
              <form class="form-signin" method="post">{% csrf_token %}
              <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required
              autofocus>
              <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
              {% for field in LoginForm %}
              <p>{% for error in field.errors %}</p>
                <p style="color: red">{{ error }}</p>
                {% endfor %}
                {% endfor%}
                {% if LoginForm.non_field_errors %}
                <div style="color: red">
                    <p>{{LoginForm.non_field_error}}</p>
                </div>
                {% endif %}
              <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
              </form>
                <div class="d-flex flex-column my-4">
                    <a class="m-auto" href="#">Reset password</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

core/templates/users/signin/profile.html
{% extends "layouts/base.html" %}
{% load static %}
{% include 'layouts/navbar.html' %}

{% block content%}
<div class="container-fluid">
    <div class="row justify-content-center">
        Hi user, {{ user.email }}
    </div>
</div>

{% endblock%}

core/templates/users/signup/register.html
{% extends "layouts/base.html" %}
{% load static %}
{% include 'layouts/navbar.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="card card-signin">
            <div class="card-body ">
                <form class="form-sign" method="POST">
                    {% csrf_token %}
                    <input type="text" name="firstname" class="form-control" id="inputFirstName" placeholder="First Name">
                    <input type="text" name="lastname" class="form-control" id="inputLastname" placeholder="Last Name" >
                    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email">
                    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Username" >
                    <input type="password" name="password1" class="form-control" id="inputPassword1" placeholder="Password" required>
                    <input type="password" name="password2" class="form-control" id="inputPassword2" placeholder="Repeat Password" required>
                    {% for field in RegisterForm %}
                  <p>{% for error in field.errors %}</p>
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}

                    {% endfor%}
                    {% if RegisterForm.non_field_errors %}
                    <div style="color: red">
                        <p>{{RegisterForm.non_field_error}}</p>
                    </div>
                    {% endif %}
                    <button class="btn btn-lg btn-primary btn-clock">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}